### ISSUE TITLE
UX - End meet button

### ISSUE THREAD

**Issue by Mr-K-AB** [Mr-K-AB/se-proj1-messenger#131]
- rename end meet button on header to close session.
- when clicked it should take you back to the screen which appears after google auth.

**Comment by gowthamgeddam** [comment]
DashboardControl and DashboardMemberControl also have end meet [button](https://github.com/Mr-K-AB/se-proj1-messenger/blob/344792128fec4751a9378edf6789361124fd14b1/src/MessengerApp/Views/DashboardControl.xaml#L85C51-L85C55).
- [x] Please decide if we should keep close session button on Header or in Dashboard. @Mr-K-AB @prathamrmn

**Comment by Mr-K-AB** [comment]
The end meet button can be kept to end the meeting. but not close the window and go to home page.

The header button can do this.

**Comment by gowthamgeddam** [comment]
This issue is closed by following PR
- PR #183
